version: '3.8'

services:
  task:
    build: ./app
    command: gunicorn core.wsgi --bind  0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/staticfiles
    ports:
      - 8000:8000
    env_file:
      - ./app/.env.dev
    depends_on:
      - task-db
  task-db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=task
      - POSTGRES_PASSWORD=task
      - POSTGRES_DB=task_dev

volumes:
  postgres_data:
  static_volume:

